---
output: word_document
---

# neolithicRC: *Eine Suchmaschine für Radiokohlenstoffdatierungen*

*Clemens Schmid (Kiel), Dirk Seidensticker (Tübingen)*

## Abstract

Der Aufschwung der Open-Data-Bewegung in den vergangenen Jahren führte zu einer Vielzahl von individuellen Daten-Publikationen und öffentlichen Datenbanken mit wissenschaftlichen Rohdaten. Diese bieten für sich betrachtet ein wichtiges Archiv für zukünftige Forschungsfragen. Der Mehrwert allerdings, der sich durch die Verschneidung solcher Datensätze in Hinblick auf Durchsuchbarkeit, Fehlerkontrolle sowie weiterführende Analysen ergeben kann, wird bislang nur zu selten genutzt.

*neolithicRC* hat sich zum Ziel gesetzt, verschiedene unter Open-Data-Richtlinien veröffentlichte Datenbanken mit Radiokohlenstoffdatierungen zusammenzuführen und diese in einer Suchmaske sowie einem WebGIS zugänglich zu machen. Die Daten sind dadurch in ihrem inhaltlichen Kontext durchsuchbar und können zudem auf einer Karte sowie in Diagrammen visuell erfasst werden.

Radiokohlenstoffdatierung ist insbesondere innerhalb der Prähistorischen Archäologie eine der wesentlichen Methoden zur absolut- und relativchronologischen Rekonstruktion von Kulturgeschichte. Sie liegt vielfältigen quantitativen Modellen zugrunde, sei es nun um die 'Neolithisierung' Europas oder die 'Bantu-Expansion' im subsaharischen Afrika zu beschreiben. Die Auswahl der einzelnen Daten für ein solches Modell ist komplex und erfordert ein genaues Verständnis der archäologischen Fragestellung. Kritik an den genannten Modellen setzt daher meist beim Datensatz an. Um jedoch eine Diskussion über ihn führen zu können, muss der Datensatz allgemein zugänglich, gut kontextualisiert und weitreichend standardisiert sein. Andernfalls kann keine systematische Evaluation stattfinden. Es kann dabei nicht genügen, nur jene Datenauswahl zu betrachten, die letzten Endes in einem Modell verarbeitet wurde, sondern nachvollziehbar auch jene, die nicht integriert wurden. Eine unabhängige, ungefilterte und unkomplizierte Schnittstelle kann in beschriebenem Forschungsprozess von der Modellbildung über die Publikation bis zum fachwissenschaftlichen Diskurs nutzbringend eingebunden werden. Sie erlaubt es, alternative und neue Modelle zu entwickeln.

Gegenwärtig speist sich der Datenbestand in *neolithicRC* aus vier Datenbanken (CALPAL, RADON, EUROEVOL und aDRAC) mit zusammen ca. 35.000 individuellen Einträgen, die neben Europa und dem Vorderen Orient auch das subsaharische Afrika abdecken. Eine Entfernung von Dubletten nimmt *neolithicRC* bewusst nicht vor, um eine Beurteilung des Potentials der einzelnen Quelldatenbanken für bestimmte Fragestellungen nicht einzuschränken.

*neolithicRC* ist größtenteils in der Statistikprogrammiersprache R umgesetzt. Die WebGIS Applikation basiert auf dem Shiny framework. Das Projekt ist modular aufgebaut -- individuelle Anpassungen für zu integrierende Datensätze können relativ einfach umgesetzt und Datenmanipulationswerkzeuge beliebig in die Vorbereitungspipeline eingehängt werden. Da die gesamte Entwicklung über git/github erfolgt ([github.com/nevrome/neolithicR](https://github.com/nevrome/neolithicR)), besteht neben Dokumentation und Transparenz auch für Dritte die unmittelbare Möglichkeit mitzuwirken oder eigene Projektideen abzuleiten.

Die Anwendung wird auf den Servern des eScience-Center der Eberhard Karls Universität Tübingen bereitgestellt: [www.neolithicrc.de](http://www.neolithicrc.de/)

## Antrag Reisestipendium Clemens Schmid B.A.

Ich studiere Historische und Prähistorische Archäologie in einem Masterprogramm der CAU-Kiel. *neolithicRC* ist als unabhängiges, studentisches Projekt entstanden und wird in diesem Rahmen gepflegt. Mitentwickler sind Dirk Seidensticker, M.A. (Tübingen) und Dr. Bernhard Weninger (Köln). Ansprechpartner, mit denen ich die aktuelle Projektphase diskutiert habe, sind u.a. Dr. Martin Hinz (Kiel) und Dr. Christoph Rinne (Kiel).    
